### ISSUE TITLE
Support case-insensitive regexps

### ISSUE THREAD

**Issue by PetrGlad** [miner/strgen#1]
Flag `(?i)` makes rest of regex case insensitive. E.g. `#"a(?i)B"` matches `"ab"`, `"aB"` but does not match `"AB"` (see https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html#CASE_INSENSITIVE).

It would be nice to have support for it, or some alternative way to generate strings for case-insensitive regexps, so characters are generated in both lower and upper case.

**Comment by WhittlesJr** [comment]
2021 bump

**Comment by miner** [comment]
This looks hard to implement properly given the current code.  The work-around would be to use #"a[Bb]" notation.

Would it be useful to have limited support for just an initial flag?  I was thinking just at the beginning of the regex so it's all case-insensitive or not.  That is, only #"(?i)regex".   Supporting the full use of flags would be a lot more work.  Flags can be embedded anywhere and turned on and off.  They also can be applied to subexpressions. #"x(?i:subex)(?i)y(?-i)z"  The general case is too much work (for me to do).

If the start-only option would be useful, I could give that a try.  I hesitate to do a partial feature as limitations may cause unpleasant surprises.  If someone else wants to work on this, I would welcome patches.

**Comment by WhittlesJr** [comment]
The single flag option is exactly what I need for my use case

**Comment by miner** [comment]
I changed my mind a bit.  Maybe it's better to provide a case-insensitive generator as an additional API.  That way, there's less confusion about the supported regex syntax.  Here's some code that you can test for me:

```clojure
(require '[miner.strgen :as strgen])
(require '[clojure.test.check.generators :as gen])
(require '[clojure.string :as str])

(defn gen-mixed-case [s]
  (gen/fmap (fn [ups] (str/join (map (fn [c up?]
                                       (if up? (str/upper-case c) (str/lower-case c)))
                                     (seq s)
                                     ups)))
            (gen/vector gen/boolean (count s))))
  
(defn gen-case-insensitive [s]
  (gen/one-of [(gen/return s)
               (gen/return (str/capitalize s))
               (gen/return (str/upper-case s))
               (gen/return (str/lower-case s))
               (gen-mixed-case s)]))


;; new for public use
(defn case-insensitive-string-generator
  "Like `string-generator` but case-insensitive so it generates upper and lowercase
  variations on the given regex."
  
  ([regex] (gen/bind (strgen/string-generator regex) gen-case-insensitive))

  ([regex or-more-limit]
   (gen/bind (strgen/string-generator regex or-more-limit) gen-case-insensitive)))
```

**Comment by miner** [comment]
I simplified the code a bit and pushed a new release.  Find `case-insensitive-string-generator` in version 0.2.0, now on Clojars.
