### ISSUE TITLE
CLJS support

### ISSUE THREAD

**Issue by mike-hewitson** [miner/strgen#4]
It would be great if you'd implement as cljc so we could use across clojure and clojurescript.

**Comment by miner** [comment]
It ought to work, but there are some regex differences between Clojure and CLJS so we would have to be careful about testing.  Patches welcome.

**Comment by miner** [comment]
I made a first pass at CLJS support.  strgen 0.1.6-alpha1

**Comment by mike-hewitson** [comment]
Thanks, Steve. Done some initial testing and it works for me.

**Comment by miner** [comment]
version 0.1.7 was released with CLJS support
