### ISSUE TITLE
support backslashing { and } 

### ISSUE THREAD

**Issue by andrewguy9** [miner/strgen#7]
Similar to #6, I'm trying to build regex with literal \{ and \}.

Dot works: `(gen/generate (sg/string-generator  #"\."))` -> "."

Open curly brace fails: `(gen/generate (sg/string-generator  #"\{"))` -> `;!!CompilerException clojure.lang.ExceptionInfo: Unsupported backslash char { {:unsupported-backslash \{}, compiling:(:175:1)`

The fix probably looks similar to https://github.com/miner/strgen/commit/8c932e38950a80a313f29b6f5aabe9fa9750336e 

As with #6, the work around is to add use `[{]` rather than `\{`.

**Comment by miner** [comment]
Yes.  I think the general policy should be any character that is special for `parse-chars` should be a literal after a backslash.  I added the curly braces {} and pipe | chars to the list.  Version 0.1.8 is now on Clojars.  I'm going to close the bug, but let me know if there's a problem.

**Comment by andrewguy9** [comment]
Worked for me! Thanks for quick turn around!
