### ISSUE TITLE
Dependency error in 0.2.1

### ISSUE THREAD

**Issue by zackteo** [miner/strgen#8]
Hello, I will get the following error when trying to do `lein deps` after adding `[com.velisco/strgen "0.2.1"]` to my project.clj

Could not find artifact org.clojure:alpha.spec:jar:0.2.177-SNAPSHOT

Based on the latest commits, I would assume it is fixed in `0.2.3` but it is not available on clojars

**Comment by miner** [comment]
I can't remember the details, but at one point spec.alpha changed and I tried to adapt.  However, it seemed like I was introducing some unnecessary dependencies so I didn't release a jar.  I tried to clean things up a bit today and released strgen 0.2.4.  If you still have problems, please give me your results for `lein classpath` and `lein test` and I will try to figure out what's wrong.  My current understanding is that spec should only come from the particular version of Clojure, not loaded separately.  I tested with Clojure 1.10.3 and Clojure 1.11.0-rc1.

**Comment by zackteo** [comment]
`0.2.4` works for me now :) No more dependency issues. Thanks!
