### ISSUE TITLE
Spurious deps in 0.2.4 

### ISSUE THREAD

**Issue by nathell** [miner/strgen#9]
Hey Steve, thanks for the great library!

Looks like [0.2.4’s pom.xml in Clojars](https://repo.clojars.org/com/velisco/strgen/0.2.4/strgen-0.2.4.pom) includes some spurious dependencies (expound, clj-java-decompiler, criterium, clj-memory-meter) that are not there in project.clj, nor do they seem to be used by the code. I wonder if that’s due to some Leiningen plugins in your :user profile that sneak in these additional deps when you release?

**Comment by miner** [comment]
I will have to investigate.  I think you're correct that it has something to do with my user profile.

**Comment by miner** [comment]
I pushed a new Clojars release with a clean pom.  Version 0.2.5 should be the same without the spurious dependencies.
